# Generated by Django 2.2 on 2019-05-28 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('codigo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('endereco', models.CharField(max_length=50)),
                ('titulacao', models.CharField(max_length=20)),
                ('nfunc', models.CharField(max_length=20)),
                ('fone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('notaf', models.FloatField()),
                ('faltas', models.IntegerField()),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siga.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siga.Matricula')),
            ],
        ),
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.DateTimeField()),
                ('carga', models.FloatField()),
                ('horario', models.CharField(max_length=14)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siga.Disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siga.Professor')),
            ],
        ),
    ]
